
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: hello-spring-cloud
  zipkin:
    base-url: http://localhost:9411/
