server:
  port: 8087
spring:
  application:
    name: client1
eureka:
  client:
    service-url:
#      Об▓ролл─хпои
      defaultZone : http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true