spring:
  application:
    name: zipkint


server:
  port: 9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
